#+BEGIN_COMMENT
Information on installing, troubleshooting, using CUTEst
#+END_COMMENT

#+OPTIONS: ^:nil


* CUTEst
CUTEst (Constrained and Unconstrained Testing Environment with Safe Threads)
is a testing environment for numerical optimization.  The package reads
problems in SIF format and passes it to an optimiation solver.  The authors
of this package are Nick Gould, Dominique Orban and Philippe Toint.

- <<cutest paper>>N. Gould, D. Orban, Ph. Toint. "CUTEst: a Constrained and Unconstrained
  Testing Environment with safe threads for mathematical optimization", \\
  Computational Optimization and Applications, 60(3): 545--557, 2015.
  https://doi.org/10.1007/s10589-014-9687-3

CUTEst is comprised of three packages: archdefs, SIFDecode, and CUTEst, all
of which are are hosted on github (https://github.com/ralna/CUTEst).

Currently, there are forked versions of CUTEst, SIFDecode, and ARCHDefs,
which have been modified to work with MacOS, ifort (Intel Fortran compiler),
and current versions of Matlab.  These are also on github and can be cloned using the following commands:
#+BEGIN_SRC
>> git clone https://github.com/ucsd-optimizers/CUTEst.git
>> git clone https://github.com/ucsd-optimizers/SIFDecode.git
>> git clone https://github.com/ucsd-optimizers/ARCHDefs.git
#+END_SRC

For the SIF problem files:
#+BEGIN_SRC
>> git clone https://bitbucket.org/optrove/sif
#+END_SRC

** Requirements

*Software/Compilers*
| Compilers                    | Notes                                                                                                                                                                                                  |
|------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| GNU gfortran compiler        | On MacOS, can be installed via Macports.                                                                                                                                                               |
| Intel Fortran compiler ifort | This is required if you want to use CUTEst with Matlab.  Intel Parallel Studio XE is available for free to students -- https://software.intel.com/en-us/parallel-studio-xe/choose-download/student-mac |
|                              |                                                                                                                                                                                                        |

*Environment Variables*
| Variable   | Description                         | Example                                   |
|------------+-------------------------------------+-------------------------------------------|
| $ARCHDEFS  | Location of the archdefs directory  | ARCHDEFS=/Users/me/cutest/ARCHDefs        |
| $SIFDECODE | Location of the sifdecode directory | SIFDECODE=/Users/me/cutest/SIFDecode      |
| $CUTEST    | Location of the cutest directory    | CUTEST=/Users/me/cutest/CUTEst            |
| $MYMATLAB  | Location of Matlab                  | MYMATLAB=/Applications/MATLAB_R2019a.app/ |
| $MASTSIF   | Location of the SIF files directory |                                           |

** Installation of CUTEst
Go into $CUTEST (the CUTEst directory) and run the install script with the
following commands:
#+BEGIN_SRC
>> cd $CUTEST
>> $ARCHDEFS/install_optsuite
#+END_SRC
Follow the prompts.  On MacOS, choose "64-bit MacOS".  On Linux, choose "PC
with generic 64-bit processor", then "Linux".  If installing with Matlab and
MacOS, choose "R2015a or later".

By default, our forked version of CUTEst will use the Intel Fortran ifort
compiler to generate the CUTEst/Matlab interface.


*_After installing CUTEst_*, you will need to set two more environment
variables in your .bashrc file:

| Variable      | Description                                                |
|---------------+------------------------------------------------------------|
| $MYARCH       | The architecture that CUTEst has been installed for        |
| $MYMATLABARCH | The architecture that CUTEst+Matlab has been installed for |
These variables consist of 3 components that depend on the system you're
on.  On MacOS with gfortran, it should be ~mac64.osx.gfo~ (gfortran) or
~mac64.osx.ifr~ (ifort).  On Linux, ~pc64.lnx.gfo~ (gfortran) or
~pc64.lnx.ifr~ (ifort).

You can install different configurations (i.e., use different compilers) of
CUTEst on the same computer.  For example, if you install CUTEst with
gfortran and also with ifort, you can switch between the two by changing
$MYARCH/$MYMATLABARCH.

Your software will have to compiled with the same compiler as the version
used by CUTEst.


** Testing the CUTEst installation

*_For non-Matlab CUTEst_*, run the following command to test that your
installation was successful:
#+BEGIN_SRC
>> runcutest -p gen77 -D HS118
#+END_SRC
This command tells CUTEst to decode problem HS118 and use the package "gen77"
(in this case, "gen77" is a dummy package included in CUTEst).  You should
see the following:

#+BEGIN_SRC
  ********************************
  *                              *
  *       HELLO FROM GEN!        *
  *     (DOUBLE PRECISION)       *
  *                              *
  ********************************

  OPTIMAL SOLUTION FOUND
  THE ANSWER IS    41.999999999999901
  ************************ CUTEst statistics ************************
  Package used             :  GEN
  Variant                  :  name of a variant, if needed
  Problem                  :  HS118
  # variables              =              15
  # constraints            =              17
  # linear constraints     =              17
  # equality constraints   =               0
  # inequality constraints =              17
  # bounds                 =              15
  # objective functions    =            0.00
  # objective gradients    =            0.00
  # objective Hessians     =            0.00
  # constraints functions  =            0.00
  # constraints gradients  =            0.00
  # constraints Hessians   =            0.00
  Exit code                =               0
  Final f                  =   0.4200000E+02
  Set up time              =            0.00 seconds
  Solve time               =            0.00 seconds
 ******************************************************************
#+END_SRC

For more Fortran/CUTEst function, refer to Appendix A in the [[CUTEst paper]].
You can also use the ~man~ command at the terminal to get more information
on a particular CUTEst function.  For example:
#+BEGIN_SRC
>> man cutest_cofg
  NAME
         CUTEST_cofg - CUTEst tool to evaluate function value and possibly gradient.

  SYNOPSIS
         CALL CUTEST_cofg( status, n, X, f, G, grad )
  ...
#+END_SRC

*_For Matlab CUTEst_*, start Matlab and run the following commands:
#+BEGIN_SRC
>> unix('cutest2matlab HS118');
>> prob = cutest_setup()
prob =

         n: 15
         m: 17
      nnzh: 15
      nnzj: 39
         x: [15x1 double]
        bl: [15x1 double]
        bu: [15x1 double]
         v: [17x1 double]
        cl: [17x1 double]
        cu: [17x1 double]
    equatn: [17x1 logical]
    linear: [17x1 logical]
      name: 'HS118     '
#+END_SRC
The first command decodes the problem ~HS118~.  The second command extract the
problem information into a Matlab variable called ~prob~.  ~prob~ should
contain several components.  In particular, ~prob.n~ and ~prob.m~ are the number
of variables and constraints in the problem (for HS118, these should be 15
and 17).

For more Fortran/CUTEst function, refer to Appendix B in the [[CUTEst paper]].
In Matlab, you can also use the ~help~ command.  For example,
#+BEGIN_SRC
>> help cutest_obj
  Return function value and gradient if requested.
  Usage:  f = cutest_obj(x)  or  [f,g] = cutest_obj(x)
#+END_SRC

** Troubleshooting
- Errors encountered when compiling a Matlab mex-file or when installing CUTEst with Matlab:
  - Error: =No supported compiler or SDK was found=
  - Error: =-arch not recognized=

  For both of these, you need to edit a few xml files in Matlab.  They are
  located in =<matlab>/bin/<sys>/mexopts/=, where <matlab> is the the path
  to the version of Matlab you are using, and <sys> depends on what system
  you're on.  For example, on MacOS with 2015aSP1, the files are in
  =/Applications/MATLAB_R2015aSP1.app/bin/maci64/mexopts/=.

  In this directory, you will see xml files for gfortran, clang, and clang++.
  You will need to edit these files and may need to change the permission in
  order to give you /write/ access (see [[file permissions]]).

  _For the first error_, open up these files and search for lines with
  MacOS10.10.sdk.  You will need to add lines for MacOSX10.12.sdk (for
  Xcode8) wherever you see lines with MacOS10.10.sdk.  You should add 4
  lines in total.

  _For the second error_, search the xml files for =-arch x86_64= and remove
  them from all of the xml files.

** Using CUTEst

** Creating a CUTEst interface for your own optimization solver
:PROPERTIES:
:ALT_TITLE: Creating a CUTEst interface
:END:
