#+BEGIN_COMMENT
Information on installing, troubleshooting, using CUTEst
#+END_COMMENT

#+OPTIONS: ^:nil

* CUTEst

CUTEst (Constrained and Unconstrained Testing Environment with Safe Threads)
is a testing environment for numerical optimization.  The package reads
problems in SIF format and passes it to an optimiation solver.  The authors
of this package are Nick Gould, Dominique Orban and Philippe Toint.

- N. Gould, D. Orban, Ph. Toint. "CUTEst: a Constrained and Unconstrained
  Testing Environment with safe threads for mathematical optimization", \\
  Computational Optimization and Applications, 60(3): 545--557, 2015.
  https://doi.org/10.1007/s10589-014-9687-3

CUTEst is comprised of three packages: archdefs, SIFDecode, and CUTEst.  To
download archdefs, SIFDecode and CUTEst:
#+BEGIN_SRC
>> svn checkout --username anonymous http://ccpforge.cse.rl.ac.uk/svn/cutest/archdefs/trunk ./archdefs
>> svn checkout --username anonymous http://ccpforge.cse.rl.ac.uk/svn/cutest/sifdecode/trunk ./sifdecode
>> svn checkout --username anonymous http://ccpforge.cse.rl.ac.uk/svn/cutest/cutest/trunk ./cutest
#+END_SRC

For the SIF problem files:
#+BEGIN_SRC
>> svn checkout --username anonymous http://ccpforge.cse.rl.ac.uk/svn/cutest/sif/trunk ./sif
#+END_SRC

** Installing CUTEst

Before installing the package, you will need to set a few environment
variables to make sure everything runs smoothly.

| Variable   | Value                               | Example                                    |
|------------+-------------------------------------+--------------------------------------------|
| $ARCHDEFS  | Location of the archdefs directory  |                                            |
| $SIFDECODE | Location of the sifdecode directory |                                            |
| $CUTEST    | Location of the cutest directory    |                                            |
| $MYMATLAB  | Location of Matlab                  | MYMATLAB=/Applications/MATLAB_R2015a.app/  |
| $MASTSIF   | Location of the SIF files directory |                                            |

You also need to make sure you have Fortran (gfortran) and C (gcc) compilers
installed on your machine.

_If you are using CUTEst with Matlab_, you need to have gcc/gfortran version
4.3.  You can install it via macports: ~port install gcc43~.  You will also
need to create symbolic links named "gfortran-4.3" and "gcc-4.3" somewhere
in your $PATH to point to the actual 4.3 compilers because that is what
CUTEst will look for (see [[symbolic links][symbolic link creation]]).

To install CUTEst, go into $CUTEST (the cutest directory) and run the
install script:
#+BEGIN_SRC
>> cd $CUTEST
>> $ARCHDEFS/install_optsuite
#+END_SRC
The script will ask you several questions about your system.  If you are not
using CUTEst with Matlab, choose the "gfortran" and "gcc" options.

** Troubleshooting
- Errors encountered when compiling a Matlab mex-file or when installing CUTEst with Matlab:
  - Error: =No supported compiler or SDK was found=
  - Error: =-arch not recognized=

  For both of these, you need to edit a few xml files in Matlab.  They are
  located in =<matlab>/bin/<sys>/mexopts/=, where <matlab> is the the path
  to the version of Matlab you are using, and <sys> depends on what system
  you're on.  For example, on MacOS with 2015aSP1, the files are in
  =/Applications/MATLAB_R2015aSP1.app/bin/maci64/mexopts/=.

  In this file, you will see xml files for gfortran, clang, and clang++.
  You will need to edit these files and may need to change the permission in
  order to give you /write/ access (see [[file permissions]]).

  _For the first error_, open up these files and search for lines with
  MacOS10.10.sdk.  You will need to add lines for MacOSX10.12.sdk (for
  Xcode8) wherever you see lines with MacOS10.10.sdk.  You should add 4
  lines in total.

  _For the second error_, search the xml files for =-arch x86_64= and remove
  them from all of the xml files.

** Using CUTEst

** Creating a CUTEst interface for your own optimization solver
:PROPERTIES:
:ALT_TITLE: Creating a CUTEst interface
:END:
